tasks:
  - name: Set up Rust (Nightly)
    init: |
      rustup toolchain install nightly
      rustup default nightly
      rustup target add wasm32-unknown-unknown --toolchain nightly
      cargo install cargo-leptos
    command: echo "Rust (nightly) and Leptos are ready!"

  - name: Set up Node.js and Tailwind CSS
    init: |
      yarn install
    command: echo "Node.js and Tailwind CSS are ready!"

  - name: Build and start Leptos dev server
    command: |
      cargo leptos watch

ports:
  - port: 3000
    onOpen: open-browser
  - port: 3001 # Leptos SSR server (if applicable)
    onOpen: open-browser

vscode:
  extensions:
    - rust-lang.rust-analyzer # Rust language support
    - bradlc.vscode-tailwindcss # Tailwind CSS IntelliSense
    - usernamehw.errorlens # Highlight errors in code